
Building OpenSess
=================

Unpack opensess-source-XX.XX.zip (where "XX.XX" is the release
number) into any directory.
Build the class files with the following command from the 
installation directory:

  javac openSess/*.java

OpenSess can now be started as follows:

  java openSess.OpenSess

Requirements
============

You must have a Java Runtime Environment (JRE) and a
Java Software Development Kit (SDK) installed. 
OpenSess was tested with J2SE v1.5.0.

